
FROM openjdk:17

LABEL maintainer="TechCareer Fullstack Spring Boot Bootcamp Todo App Project Backend"

ADD TechCareer_FullStackTodoAppApplication1.jar backend.jar

ENTRYPOINT [ "java", "-jar", "/backend.jar" ]

EXPOSE 2222 9999